### ISSUE TITLE
questions about helpers.flop_count

### ISSUE THREAD

**Issue by refraction-ray** [dgasmith/opt_einsum#138]
I am confused with `helpers.flop_count` method.
https://github.com/dgasmith/opt_einsum/blob/77568118fe1b198bd15b27f6766d32be16ae2e4e/opt_einsum/helpers.py#L160-L164

The function gives me different results from docstring example.
```python
flop_count('abc', False, 1, {'a': 2, 'b':3, 'c':5}), flop_count('abc', True, 2, {'a': 2, 'b':3, 'c':5})
(30, 60)
```

I also want to know more about the meaning of the function inputs. Are the counting is supposed to calculate flop of contracting all indices in ``idx_contraction`` between ``num_terms`` of tensors? What is the ``inner`` switch for?

**Comment by jcmgray** [comment]
Ah I think the docstring needs to be updated.

The fundamental logic is so: the product of all the dimensions involved (``idx_contraciton``) is all the different combinations of elements that needs to be considered. If there are two terms you just need one multiplication per combinations, but two for ``num_terms==3`` etc. Finally, if any of the indices are contracted (there's an ``inner`` product), you need to not only multiply numbers but also add them to something.

The logic is appropriate for real tensors and e.g. a standard looping implementation of einsum. One complication is that for complex data multiplication is not the same cost as addition, and also some cpu instruction allow multiply+add in one operation. And of course real world performance is tied to a whole huge array of implementation details! 

I might be in favor of simplifying ``flop_count`` to ``op_count`` (just the product of the dimensions involved) but this might also be a breaking change, and in any case, for order of magnitude accuracy and in terms of scaling, ``flop_count`` is generally pretty good.

**Comment by refraction-ray** [comment]
Did you mean that `inner` keyword is actually not a bool, but rather a set of indices that to be contracted?
e.g. The flop count (in the sense of order of magnitude) for  a_ijb_jk is actually `flop_count("ijk", "j", 2, size_list)`. Am I understanding right?

**Comment by jcmgray** [comment]
No the inner kwarg is technically a bool, you either need to add the newly computed multiplication to something or not. You can supply the set of inner indices though as this evaluates to true if not empty.
________________________________

**Comment by refraction-ray** [comment]
Thanks, I see. I just found the flop count is not affected by how many indices are traced. For example, these is no difference in terms of flops for ``ijk,jkm->im`` and ``ijk,km->ijm``, both are 2n^4. And even the leading order of  ``ijk,km->im`` is also 2n^4 with some n^3 subleading terms. So I guess there is no big issue as long as one provides all the indices ``ijkm`` and there are indeed something to be traced ``True`` to avoid ambguity of something like ``ij,km->``.
