### ISSUE TITLE
Possible JOSS paper

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#14]
I have been playing around with the idea of submitting this project as a paper to [The Journal of Open Source Software](http://joss.theoj.org). Once the documentation is fully ported over to ReadTheDocs the process should be relatively straightforward.

I would be curious if any other contributors would be interested in being on the paper as well. I think @jcmgray should be especially for the latest contributions. Any other thoughts here?

**Comment by jcmgray** [comment]
Sound great to me. What would the requirements be and on my part? Could help with docs.

**Comment by dgasmith** [comment]
Beyond finishing the documentation and writing up a pretty short ~1 page description of the project and use cases there isn't much to do. If you could help pushing the docs to the current RTD build that would be great.

I can make a PR for the `paper.md` description next week and we can go from there.

**Comment by dgasmith** [comment]
@jcmgray I think we are at the point in docs/code for this to go through. Any objections?

**Comment by jcmgray** [comment]
No all good from me. Of the remaining issues I had a little hack at constant arguments, but it didn't seem super simple to implement so I've left it for now.
