### ISSUE TITLE
cuTensor with cupy

### ISSUE THREAD

**Issue by cnk113** [dgasmith/opt_einsum#144]
Hello,

Are you considering integrating cuTensor at this point? It looks like you were considering it before #97. 
cuTensor is released with CUDA 11, and seems to be a massive speedup., Also the cutensor module in [cupy](https://github.com/cupy/cupy/blob/master/cupy/cutensor.py) looks like it's fully integrated at this point. 

Best

**Comment by jcmgray** [comment]
The way things are set up means that if ``cupy`` (or any other library) has implemented it (in ``cupy.tensordot`` and ``cupy.einsum``) then there are no changes required on ``opt_einsum``'s end! Just supply ``cupy`` arrays, or supply ``backend='cupy'`` to a ``ContractExpression``.

It's currently a little fiddly to install ``cupy`` with cutensor but I have tested that this is working. One thing to note is that ``opt_einsum`` creates high dimensional intermediates and ``cutensor`` currently only supports 12 dimensions.
