### ISSUE TITLE
Test fails with newer numpy

### ISSUE THREAD

**Issue by avdv** [dgasmith/opt_einsum#147]
Hi.

We've encountered that after upgrading numpy that builds would fail because numpy no longer raises a `TypeError` for invalid order parameters, but a `ValueError` instead.

See https://nix-cache.s3.amazonaws.com/log/zn2qyadxc7l1xrwn39wbrmnvjqj1mg9w-python3.7-opt_einsum-3.2.1.drv

Numpy was upgraded from 1.18.5 -> 1.19.0

**Comment by dgasmith** [comment]
Thanks for the report. I worked on this in NumPy so I'm a bit surprised at the change in behavior since we added an explicit test there to check on the raises. Let me look into this.

**Comment by avdv** [comment]
See https://github.com/numpy/numpy/commit/35b0a051c19265f5643f6011ee11e31d30c8bc4c

**Comment by dgasmith** [comment]
Great! *I* didn't cause that issue :) We can patch this up quickly.

**Comment by dgasmith** [comment]
This is patched in #149. I will put out a minor release today after I fix one more bug.

**Comment by dgasmith** [comment]
v3.3.0 is out.

**Comment by avdv** [comment]
Thank you! (I am basically  offline right now, that's why the late response)
