### ISSUE TITLE
Remove 'remaining' from PathInfo? (incurs n^2 memory overhead)

### ISSUE THREAD

**Issue by jcmgray** [dgasmith/opt_einsum#148]
When building the ``contraction_list``, ``opt_einsum`` handles a list of 'remaining'  terms, and at each new step these are copied (``input_list`` below):

https://github.com/dgasmith/opt_einsum/blob/2cbd28e612ff0af54656c34d7f6c239efe524b12/opt_einsum/contract.py#L306

A single, consumed version of this list is needed for constructing the items in the contraction list. However all the copies at each stage are not needed in the actual contraction (``_core_contract``) function - they are just for printing in the ``PathInfo`` object. 

The problem is that each copied list of remaining terms is of average length `n / 2` and there are generally `n - 1` of them, incurring a `n^2` memory overhead, which caused problems for us (10s of gigabytes of problems!) in some large contractions. Here's an extreme sample of such a gigantic ``PathInfo``:

![Screenshot from 2020-07-15 19-11-55](https://user-images.githubusercontent.com/8982598/87640894-486a1400-c73f-11ea-98a1-dab04d3e02f8.png)

With 50 contractions each of several thousand tensors there was a total of nearly 100,000,000 'remaining' lists of strings.

I'd suggest either:
* a) *Easiest* - we just remove the 'remaining' terms from the ``PathInfo`` object, I'd be fine with this but possibly its useful information for others?
* b) *Medium* - the 'remaining' terms are only accumulated below a certain threshold size
* c) *Hardest* - they are generated lazily (and maybe optionally) by the ``PathInfo`` object upon request only (e.g. printing)

**Comment by dgasmith** [comment]
Interesting trouble :) 

I see people use the PathInfo object a lot for printing on forums and StackOverflow so I'm hesitant to make changes there. I think b) is fairly easy to do and would still be useful for those looking at the contraction.
