### ISSUE TITLE
Could opt_einsum be employed in PyTorch when the torchscript was used to compile the code?

### ISSUE THREAD

**Issue by zhangylch** [dgasmith/opt_einsum#156]
As mentioned in the title, I want to use torchscript to compile the Pytorch code, which can be used for production in C++ environments. I just want to know if opt_einsum can be used alongside torchscript?

**Comment by jcmgray** [comment]
I'm pretty sure you can `torch.jit.trace` through (albeit with some warnings about shapes) so the answer is [probably](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting).

**Comment by zylustc** [comment]
what about the torch.jit.script？发自我的华为手机-------- 原始邮件 --------发件人： Johnnie Gray <notifications@github.com>日期： 2021年2月10日周三 02:55收件人： dgasmith/opt_einsum <opt_einsum@noreply.github.com>抄送： zyl12138 <ylzustc@mail.ustc.edu.cn>, Author <author@noreply.github.com>主    题： Re: [dgasmith/opt_einsum] Could opt_einsum be employed in PyTorch when the torchscript was used to compile the code? (#156)
I'm pretty sure you can torch.jit.trace through (albeit with some warnings about shapes) so the answer is probably.

**Comment by jcmgray** [comment]
Sorry it wasn't very clear but [if you follow the link in my previous comment](https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting) then it says you can call traced functions from script functions.

https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting

thus ... probably, though I haven't tried.

**Comment by zylustc** [comment]
ok, I will try these. Thanks for your help发自我的华为手机-------- 原始邮件 --------发件人： Johnnie Gray <notifications@github.com>日期： 2021年2月10日周三 07:58收件人： dgasmith/opt_einsum <opt_einsum@noreply.github.com>抄送： zyl12138 <ylzustc@mail.ustc.edu.cn>, Author <author@noreply.github.com>主    题： Re: [dgasmith/opt_einsum] Could opt_einsum be employed in PyTorch when the torchscript was used to compile the code? (#156)
Sorry it wasn't very clear but if you follow the link in my previous comment then it says you can call traced functions from script functions.
https://pytorch.org/docs/stable/jit.html#mixing-tracing-and-scripting
thus ... probably, though I haven't tried.

**Comment by Linux-cpp-lisp** [comment]
At least for a simple example, tracing does appear to work:
```python
In [1]: import torch
im
In [2]: import opt_einsum

In [3]: a, b = torch.randn(5, 6), torch.randn(6, 9)

In [4]: def f(x, y):
   ...:     return opt_einsum.contract('ij,jk->ik', x, y)
   ...: 

In [6]: g = torch.jit.trace(f, (a, b))
opt_einsum/contract.py:231: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  dim = int(sh[cnum])
opt_einsum/blas.py:76: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if shapes[0][input_left.find(c)] != shapes[1][input_right.find(c)]:

In [8]: torch.allclose(g(a, b), f(a, b))
Out[8]: True

In [9]: a2, b2 = torch.randn(8, 3), torch.randn(3, 4)

In [10]: torch.allclose(g(a2, b2), f(a2, b2))
Out[10]: True
```

**Comment by Linux-cpp-lisp** [comment]
Another approach, which I've been developing in [`opt_einsum_fx`](https://github.com/Linux-cpp-lisp/opt_einsum_fx), is using the new PyTorch FX library to rewrite the computation graph with optimized einsums from `opt_einsum` (and a few other transformations). Because it rewrites the compute graph using FX, the optimized compute graph can be passed directly to `torch.jit.script`. 

(Like tracing through `opt_einsum.contract`, this approach still involves a fixed contraction path based on a set of example inputs.)

**Comment by zylustc** [comment]
> Another approach, which I've been developing in [`opt_einsum_fx`](https://github.com/Linux-cpp-lisp/opt_einsum_fx), is using the new PyTorch FX library to rewrite the computation graph with optimized einsums from `opt_einsum` (and a few other transformations). Because it rewrites the compute graph using FX, the optimized compute graph can be passed directly to `torch.jit.script`.
> 
> (Like tracing through `opt_einsum.contract`, this approach still involves a fixed contraction path based on a set of example inputs.)

Thanks for your kind help

**Comment by dgasmith** [comment]
Closing, opt_einsum_fx and torch.jit.trace are both good options.
