### ISSUE TITLE
Contraction route "ipx, iqx -> pq" probably slow and not multi-threading most time

### ISSUE THREAD

**Issue by ajz34** [dgasmith/opt_einsum#157]
Hi devs!

It seems that contraction route `ipx, iqx -> pq` could be slow, consuming much memory and not utilizing multi-threading most of the time (not all the time).
If I manually transpose, or subsequently allocate extra memory to transposed tensor, it could be much faster.
Tensor tested in the following code is (150, 150, 10000). Actually I'm handling much larger tensor (~400, ~400, ~80k), and problem is more serious for that large tensor.

Given 16GB memory and 4 threads for personal computer in Linux, performance lists below: (tested by `%%timeit -n 3` in jupyter notebook)
```python
import numpy as np
import opt_einsum
# Initialization
dim_i, dim_q, dim_x = 150, 150, 10000
t = np.random.randn(dim_i, dim_q, dim_x)
# Scheme 1   2.2 s ± 157 ms
v1 = opt_einsum.contract("ipx, iqx -> pq", t, t, optimize="optimal", memory_limit=int(10**10))
# Scheme 2   2.03 s ± 69.2 ms
b = t.swapaxes(0, 1)
v2 = opt_einsum.contract("pix, qix -> pq", b, b, optimize="optimal", memory_limit=int(10**10))
# Scheme 3   1.38 s ± 38.1 ms
b = t.swapaxes(0, 1)
v3 = np.einsum("pix, qix -> pq", b, b, optimize="optimal")
# Scheme 4   686 ms ± 59.1 ms
b = t.swapaxes(0, 1).reshape(dim_q, dim_i*dim_x)
v4 = opt_einsum.contract("px, qx -> pq", b, b, optimize=True)
# Scheme 5   465 ms ± 46.9 ms
v5 = np.zeros((dim_q, dim_q))
for i in range(dim_i):
    v5 += opt_einsum.contract("px, qx -> pq", t[i], t[i], optimize=True)
```
- Scheme 1: Naive einsum contraction with enough memory declared (numpy also performs about 2 sec);
- Scheme 2: Manually transpose the tensor, but not changing base tensor memory (i.e. `np.shares_memory(t, b) is True`);
- Scheme 3: Manually transpose the tensor, but using numpy instead;
- Scheme 4: Manually transpose the tensor, and allocate extra memory (i.e. `np.shares_memory(t, b) is False`);
- Scheme 5: Brutal for loop. This is the most efficient scheme in my testing.

In my speculation, Scheme 1 spent most time allocating memory. But I can't verify this statement.

Did I'm miss some essential optimization techniques? Or I need to transpose tensors manually to gain efficiency boost?

**Comment by ajz34** [comment]
After reading around, I found it's related to issue https://github.com/dgasmith/opt_einsum/issues/143.
And then I tried snakeviz (thanks jcmgray introducing this tool :laughing:). Rate-determining step of Scheme 1~4 should be reshape. Different reshapes paths have different timing.

This specified contraction route `ipx, iqx -> pq`, Scheme 5 does not need reshape. It's somehow weird to me. Maybe I've missed something.

**Comment by dgasmith** [comment]
The primary call that enhances the speed here is a [GEMM](https://en.wikipedia.org/wiki/Basic_Linear_Algebra_Subprograms#Level_3) which is highly optimized for matrix matrix multiplication. A tensor (generally more than two dimensions) can be "reshaped" so that GEMM generally works as the higher dimensional tensor can look like a matrix. While there are libraries that can smartly handle this reshaping such as [TBLIS](https://github.com/devinamatthews/tblis) they are not yet widely available.

A for loop (scheme 5) is a way of getting around this problem, the version that you show is particularly optimal since the tensors are laid out contiguous in memory and GEMM can be most performant.

A quick guess at what you are seeing:
Scheme 1: Pure tensordot requiring copies of both tensors before GEMM
Scheme 2: This should effectively be scheme 1 since a swap axes doesn't copy the memory
Scheme 3: Its odd to me why these would give different performance values, could you post the optimization route?
Scheme 4: A swap axes followed by a reshape copies the tensor preventing the copy to happen inside the `oe.contract` function.
Scheme 5: The optimal way of performing this contraction.

We have investigated automated for loops in the past, but as to date have yet to find a solution which is performant in all scenarios.

**Comment by ajz34** [comment]
Thanks! These tips could be useful 😄 
Actually I used to write scripts using einsum without deeper consideration. I may need to change that habit a bit 😂

Contraction path of Scheme 1 (naive) is
```
  Complete contraction:  ipx,iqx->pq
         Naive scaling:  4
     Optimized scaling:  4
      Naive FLOP count:  6.750e+10
  Optimized FLOP count:  6.750e+10
   Theoretical speedup:  1.000
  Largest intermediate:  2.250e+4 elements
--------------------------------------------------------------------------------
scaling        BLAS                current                             remaining
--------------------------------------------------------------------------------
   4           TDOT            iqx,ipx->pq                                pq->pq
```
Scheme 2 (with transpose) is almost the same to Scheme 1, except for `Complete contraction` token and underlying `BLAS`:
```
  Complete contraction:  pix,qix->pq
         Naive scaling:  4
     Optimized scaling:  4
      Naive FLOP count:  6.750e+10
  Optimized FLOP count:  6.750e+10
   Theoretical speedup:  1.000
  Largest intermediate:  2.250e+4 elements
--------------------------------------------------------------------------------
scaling        BLAS                current                             remaining
--------------------------------------------------------------------------------
   4           GEMM            qix,pix->pq                                pq->pq
```
Scheme 3 (numpy with transpose) is almost the same to Scheme 2:
```
  Complete contraction:  pix,qix->pq
         Naive scaling:  4
     Optimized scaling:  4
      Naive FLOP count:  6.750e+10
  Optimized FLOP count:  6.750e+10
   Theoretical speedup:  1.000
  Largest intermediate:  2.250e+04 elements
--------------------------------------------------------------------------
scaling                  current                                remaining
--------------------------------------------------------------------------
   4                 qix,pix->pq                                   pq->pq
```

**Comment by jcmgray** [comment]
Yeah the optimizations ``opt_einsum`` consider largely come from assessing a pairwise contraction order for 3+ tensors and ignore reshaping/copying costs etc.. As @dgasmith has detailed when it comes down to assessing a *single contraction* like here predicting performance is a lot trickier. Thought I'd just mention https://github.com/cyclops-community/ctf that I have found to be fast for large, parallel contractions and avoiding reshapes.

**Comment by dgasmith** [comment]
Closing, I don't think there are action items in here.
