### ISSUE TITLE
Taking strides into account

### ISSUE THREAD

**Issue by danpovey** [dgasmith/opt_einsum#162]
Does opt_einsum have any way of taking strides into account, and if not, might you do something like that in future?
Here's an example: suppose you want to do some kind of convolution-type operation, and you mess with strides so one input is of shape (length, kernel_length, ...) but both of those dimensions have the same stride so the rows overlap.  It might be possible in that case to evaluate sub-expressions that use the fact that the (length, kernel_length) part of the shape can be contracted temporarily into a single dimension, reducing the number of elements that must be operated on.
Even with non-overlapping strides, there might be situations where expressions can be simplified to lower-order expressions by internally contracting multiple dimensions into a single dimension like that.
There might also be situations where you could temporarily contract one or more dimensions to zero dimensions, if they had stride zero or size 1.

**Comment by danpovey** [comment]
Incidentally, at one point I was working on a tensor framework (I never finished it) in which I developed
a kind of mathematical formalism for reasoning about operations on tensors laid out with strides in memory.
See here
https://github.com/kaldi-asr/kaldi/blob/kaldi10/src/tensor/pattern.h
I'll just quote one small piece which won't make sense in isolation but will give you an intuition for the general
flavor of the framework:
```
    Reduced pattern-tuple:                                                                                                                                                                                
                      A pattern-tuple is in reduced form if there is no                                                                                                                                   
                      set-equivalent pattern-tuple which has fewer axes                                                                                                                                   
                      (defining the num_axes of a pattern-tuple as the                                                                                                                                    
                      greatest of the num_axes of the patterns in the tuple).                                                                                                                             
                                                                                                                                                                                                          
                      What this means more concretely/intuitively is that there                                                                                                                           
                      are no axes which are trivial for all patterns and can be                                                                                                                           
                      removed; and there are no pairs of axes which can be                                                                                                                                
                      combined for all patterns in the tuple.                                                                                                                                             
```

**Comment by dgasmith** [comment]
We do not currently take stride tricks into account. I suspect cases like this where a 2D array can be represented by a 1D are best handled by the calling library as it would seem that this specific structure would be difficult to detect.
