### ISSUE TITLE
Use timeit to check the performance

### ISSUE THREAD

**Issue by ghost** [dgasmith/opt_einsum#178]
Just a very basic question about using `timeit`.
From https://optimized-einsum.readthedocs.io/en/stable/#
For a python code

```
import numpy as np
dim = 10
I = np.random.rand(dim, dim, dim, dim)
C = np.random.rand(dim, dim)

def naive(I, C):
        # N^8 scaling
    return np.einsum('pi,qj,ijkl,rk,sl->pqrs', C, C, I, C, C)

def optimized(I, C):
                # N^5 scaling
    K = np.einsum('pi,ijkl->pjkl', C, I)
    K = np.einsum('qj,pjkl->pqkl', C, K)
    K = np.einsum('rk,pqkl->pqrl', C, K)
    K = np.einsum('sl,pqrl->pqrs', C, K)
    return K

%timeit naive(I, C)
```

If I run the above code `python opt.py`, suppose the filename is `opt.py`, I got 
```
    %timeit naive(I, C)
    ^
SyntaxError: invalid syntax
```
How to get it right? Thank you so much.

**Comment by jcmgray** [comment]
That's called 'magic' syntax used for ipython and jupyter notebooks (i.e not the raw python interpreter).

![image](https://user-images.githubusercontent.com/8982598/146999141-93f9314c-a237-4db2-8c53-19dec5fb94eb.png)
