### ISSUE TITLE
error in Test opt_enisum

### ISSUE THREAD

**Issue by jiaminglei-lei** [dgasmith/opt_einsum#183]
installed from source and installed successfully.
but when i tried to test it with py.test, the error comes:
![image](https://user-images.githubusercontent.com/42641278/158759786-0513936c-6d65-4e1a-b48e-3d1a85c3ef34.png)
and the backend is 'torch'.

**Comment by dgasmith** [comment]
Hi, thanks for the report. What version of torch is this and if if you rerun does it pass (i.e., is this flakey).

**Comment by dgasmith** [comment]
Closing as not currently reproducible. Please reopen if you can supply the above details.
