### ISSUE TITLE
[question]: compute contraction order and provide order at future call

### ISSUE THREAD

**Issue by rohany** [dgasmith/opt_einsum#184]
Hi, I was looking through the documentation and some issues and wanted to know if the following was possible:

I want to perform the search for a `contract` plan ahead of time, and then provide the plan to a `contract` call at some time in the future to avoid overhead from the search at the time that it is called. Is such a thing possible?

**Comment by jcmgray** [comment]
Hi @rohany, yes that is [very much possible](https://optimized-einsum.readthedocs.io/en/stable/reusing_paths.html), e.g.:
```python
expr = oe.contract_expression(eq, *shapes, optimize=opt)

x1 = expr(*arrays1)
x2 = expr(*arrays2)
```
or if you just want to keep the [more compact `path` representation](https://optimized-einsum.readthedocs.io/en/stable/path_finding.html):
```python
path, info = oe.contract_path(eq, *arrays, optimize=opt)

x1 = oe.contract(eq, *arrays1, optimize=path)
x2 = oe.contract(eq, *arrays2, optimize=path)
```
let us know if there is some specific way the docs are not clear about this at the moment!

**Comment by rohany** [comment]
Thanks for the quick response! I think that I just didn't know what to look for / what to search to find it.
