### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by alex-orca** [dgasmith/opt_einsum#215]
Hi, I am using this package (via quimb) with pytorch as a backend for large contractions. I am  able to run on 1 GPU using pytorch, but is there anyway to use multiple GPUs at once for distributed calculation of contractions? I am happy to change back end if needed!
Thanks

**Comment by jcmgray** [comment]
Hi @alex-orca, automatic distributed contraction is quite a difficult task and I'm not aware of any purely 'just switch backend' based method, though would be happy to hear if anyone knows of one! I know there is work being done on it.

One option, which hasn't made it into `opt_einsum` yet, is to use ['slicing'](https://cotengra.readthedocs.io/en/latest/trees.html#index-slicing). `cotengra` supports [automatic 'slicing'](https://cotengra.readthedocs.io/en/latest/advanced.html#basic-slicing-slicing-opts), and there is a MPI style example [here](https://github.com/jcmgray/cotengra/blob/main/examples/ex_mpi_spmd.py). The overhead can be quite dependent on the actual contraction geometry, bear in mind.

**Comment by dgasmith** [comment]
I'm closing this as out of scope. We're here to optimize the path and nothing more echoing @jcmgray's answer.
