### ISSUE TITLE
New release with Python 3.12 support?

### ISSUE THREAD

**Issue by singingwolfboy** [dgasmith/opt_einsum#221]
It appears that the `master` branch of this project supports Python 3.12, but the latest release on PyPI is [version 3.3.0](https://pypi.org/project/opt-einsum/3.3.0/), which does not include the change from #208. As a result, this project fails to build on Python 3.12 when installed from PyPI and built from source. [Homebrew is running into this problem](https://github.com/Homebrew/homebrew-core/pull/150258#issuecomment-1802485884), and its preventing us from packaging [PyTorch](https://pytorch.org) on Python 3.12.

Could we please get a new release for this project on PyPI, where the source package can be built & installed on Python 3.12?

**Comment by dgasmith** [comment]
I'm looking to release a new version shortly which includes #208. Are there other issues I should be aware of with regard to packaging?

Apologies for the (very) slow responses here.
