### ISSUE TITLE
Setup.py says install requires Numpy >= 1.7

### ISSUE THREAD

**Issue by chabazite** [dgasmith/opt_einsum#223]
Hi thank you for this wonderful package. It looks like setup.py shows install_requires as v1.7 or greater, I believe the latest version for Numpy is v1.26.0. This may be a typo.

`        install_requires=[
            'numpy>=1.7',
        ],`

**Comment by jcmgray** [comment]
I think this is just a common confusion of reading the current version as a decimal number whereas it really does mean (1, 26, 0) which is > (1, 7, 0).
