### ISSUE TITLE
Github identifier format in docs/source/conf.py

### ISSUE THREAD

**Issue by NGC2023** [dgasmith/opt_einsum#230]
Hi,
I'm currently working on packaging opt_einsum v3.3.0 for Debian. While reviewing the code, I noticed an issue with the Github identifier format in docs/source/conf.py. I've prepared a patch to address this problem.

--- a/docs/source/conf.py
+++ b/docs/source/conf.py
@@ -395,8 +395,8 @@ def setup(app):
     app.connect('autodoc-skip-member', autodoc_skip_member)
 
 extlinks = {
--    'issue': ('https://github.com/dgasmith/opt_einsum/issues/%s', 'GH#'),
--    'pr': ('https://github.com/dgasmith/opt_einsum/pull/%s', 'GH#')
++    'issue': ('https://github.com/dgasmith/opt_einsum/issues/%s', 'GH#%s'),
++    'pr': ('https://github.com/dgasmith/opt_einsum/pull/%s', 'GH#%s')
 }

**Comment by dgasmith** [comment]
@NGC2023 Thank you for the report, fortunately we have moved to mkdocs which has removed these files. We are currently preparing for another release.
