### ISSUE TITLE
[REQUEST] Release new version

### ISSUE THREAD

**Issue by EarlMilktea** [dgasmith/opt_einsum#238]
I'm long waiting for a new release with typing support.
Do you have any plans for that?

**Comment by dgasmith** [comment]
Yes, I'm planning to release this weekend.

If you are willing, integrating the current `main` branch and running `mypy` would provide very useful feedback!

**Comment by EarlMilktea** [comment]
Super! Thank you very much.

**Comment by EarlMilktea** [comment]
Confirmed. Thank you again!
