### ISSUE TITLE
Release v2.1 patch notes

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#35]
Gathering thoughts on the 2.1 patches notes and remaining TODO's.

Remaining items:
 - [x] Update README me detailing backend support
 - [x]  Switch `setup.py` to correctly read `README.md` with new PyPi markdown support (pypi markdown support).
  - [x] Add a note about citation to DOCS and end of the README.
  - [x] `auto` path option for `optimal` for n<4.

----------------
`opt_einsum` continues to improve its support for additional backends beyond `NumPy` with PyTorch

We have also published the `opt_einsum` package in the [Journal of Open Source Software](http://joss.theoj.org/papers/10.21105/joss.00753). If you use this package in your work, please consider citing us!

New features:
 - PyTorch backend support
 - Tensorflow eager-mode execution backend support

Enhancements:
 - Intermediate tensordot-like expressions are now ordered to avoid transposes.
 - CI now uses conda backend to better support GPU and tensor libraries.
 - Now accepts arbitrary unicode indices rather than a subset.
 - New `auto` path option which switches between `optimal` and `greedy` at 4 tensors.

Bug fixes:
 - Fixed issue where broadcast indices were incorrectly locked out of tensordot-like evaluations even after their dimension was broadcast.

**Comment by dgasmith** [comment]
@jcmgray Ok, I think we are ready for 2.1. Any last comments?

**Comment by jcmgray** [comment]
> @jcmgray Ok, I think we are ready for 2.1. Any last comments?

No all looks good to me!

**Comment by dgasmith** [comment]
Ok, 2.1.1 packages are up on PyP/Conda-forge and a PR for release notes.

BTW do you have a twitter handle? I usually tweet these things out.

**Comment by jcmgray** [comment]
> Ok, 2.1.1 packages are up on PyP/Conda-forge and a PR for release notes.

Nice!

> BTW do you have a twitter handle? I usually tweet these things out.

Not an active one really, yet.

**Comment by dgasmith** [comment]
Completed, closing.
