### ISSUE TITLE
Support for get_symbol(116) in Python 2

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#42]
`get_symbol(x)` currently fails in Python 2 for any `x >= 116`:
```
i = 116

    def get_symbol(i):
        """Get the symbol corresponding to int ``i`` - runs through the usual 52
        letters before resorting to unicode characters, starting at ``chr(192)``.

        Examples
        --------
        >>> get_symbol(2)
        'c'

        >>> oe.get_symbol(200)
        'Ŕ'

        >>> oe.get_symbol(20000)
        '京'
        """
        if i < 52:
            return einsum_symbols_base[i]
>       return chr(i + 140)
E       ValueError: chr() arg not in range(256)
```
Can we fix this by use `unichr()` and unicode strings in Python 2?

**Comment by dgasmith** [comment]
Surprised we do not test this already. Looking through the code, if we keep the `i<52` range the same everything should work correctly. Perhaps something like:

```
if sys.version_info >= (3, 0):
    _unichr = chr
else:
    _unichr = unichr
```

**Comment by jcmgray** [comment]
Yes I rather lazily assumed that this was only going to be used in python3 (which is what I use), so the current extra-symbol tests are disabled in python2 (e.g. [here](https://github.com/dgasmith/opt_einsum/blob/38174b231968ccf80a9be9422045bcbc6437eb51/opt_einsum/tests/test_contract.py#L166)), and I didn't look into unicode support.

But, would be great if its as simple a fix as just using ``unichr()`` without encoding decoding etc. elsewhere.

**Comment by dgasmith** [comment]
Testing skipped [here](https://github.com/dgasmith/opt_einsum/blob/38174b231968ccf80a9be9422045bcbc6437eb51/opt_einsum/tests/test_contract.py#L149) as well, can use the same change as above to test these in both Python 2/3.
