### ISSUE TITLE
v2.2 patch notes

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#45]
Gathering thoughts on the 2.1 patches notes and remaining TODO's.

Remaining items:
 - [x] Unicode support for Python 2.7 #42.
 - [x] Update changelog before releasing.
 - [x] Docs passing updating doc strings to always contain a small example.

----------------

New features:
 - (#48) Intermediates can now be shared between contractions, see [here](https://optimized-einsum.readthedocs.io/en/latest/sharing_intermediates.html) for more details.
 - (#53) Intermediate caching is thread safe.

Enhancements:
 - (#48) Expressions are now mapped to non-unicode index set so that unicode input is support for all backends.
 - (#58) Adds tensorflow and theano with shared intermediates.

Bug fixes:
 - (#41) PyTorch indices are mapped back to a small `a-z` subset valid for PyTorch's einsum implementation.

**Comment by dgasmith** [comment]
I need to do a small docs cleanup, but I think we are ready for `v2.2`. @jcmgray @fritzo any further changes that need to be made?

**Comment by fritzo** [comment]
I have no pending changes. Looking forward to this release!

**Comment by dgasmith** [comment]
Planning to mint 2.2 tonight unless there are any blockers?

**Comment by jcmgray** [comment]
The fix for #50 should just be a few lines, so I might throw a test together now and see if it's working. Not a crucial addition however, so press ahead if you want.

**Comment by dgasmith** [comment]
Up to you, I am happy to wait a few more days if you are close to a fix for #50.

**Comment by jcmgray** [comment]
I've put something together in #58, it was slightly more involved than I expected so if you or @fritzo have any comments it can always wait!

**Comment by dgasmith** [comment]
v2.2 is now on PyPI and conda-forge is currently building (~30 minutes until deploy).

Let me know if these distributions give you any issue.

**Comment by dgasmith** [comment]
No problems with the distributions reported. Closing.
