### ISSUE TITLE
NumPy Dispatch Mechanisms

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#46]
It would be a good idea to keep an eye on [NEP 18](https://www.numpy.org/neps/nep-0018-array-function-protocol.html) "A dispatch mechanism for NumPy’s high-level array." Depending on the implementation of the NEP, this could help us avoid extra code or may require us to rework how our backend technology works.

**Comment by dgasmith** [comment]
This is making progress in the NumPy ecosystem:
https://github.com/numpy/numpy/issues/12028
https://github.com/numpy/numpy/pull/12163

**Comment by fritzo** [comment]
I'm excited for NEP 18 to go through, but at the same time, I really like that opt_einsum provides a pure-python dispatch mechanism that we can essentially use for symbolic computation. I've opened #90 to explain some of these use cases.

**Comment by jcmgray** [comment]
For what its worth, I expanded the dispatch mechanism here into [autoray](https://github.com/jcmgray/autoray). I was kind of surprised nothing like that existed already (possibly I just couldn't find it!). Anyway, ``opt_einsum`` probably doesn't need another dependency like ``autoray`` just for ``tensordot`` and friends, but it might be of interest anyway.

**Comment by dgasmith** [comment]
It would be good to do, but not high on my feature set.
