### ISSUE TITLE
Support multi-threading in shared_intermediates

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#51]
Following up on https://github.com/dgasmith/opt_einsum/pull/43#issuecomment-414661988, the `shared_intermediates` cache is currently not locked.

One option would be to assign the thread id of a unique owner of the cache, such that at least thread conflicts could be detected and reported, rather than mere silent performance degradation.

**Comment by dgasmith** [comment]
`threading.get_ident()` should work for both threads and processes. We might need to see a use case to determine what we need here, @jcmgray do you have a code snippet that you are thinking of?

**Comment by jcmgray** [comment]
Here is a toy example:

```python
import opt_einsum as oe
from collections import defaultdict

# just a helper cache that tracks accesses
class CounterDict(dict):

    def __init__(self, *args, **kwargs):
        self.counts = defaultdict(lambda: 0)
        super().__init__(*args, **kwargs)
        
    def __getitem__(self, k):
        self.counts[k] += 1
        return super().__getitem__(k)


# function that uses shared_intermediates (user may not even be aware it does so)
def my_useful_function(cache=None):
    X, Y, Z = oe.helpers.build_views('ab,bc,cd')
    
    if cache is None:
        cache = CounterDict()
    
    with oe.shared_intermediates(cache):
        # do some work
        import time
        time.sleep(0.5)
        
        Oa = oe.contract('ab,bc,cd->a', X, Y, Z)
        Ob = oe.contract('ab,bc,cd->b', X, Y, Z)
        
    return [(k, v) for k, v in cache.counts.items()]
```
What we expect everytime its run:
```python
my_useful_function()
# [(('einsum', 'numpy', 'ab,bc->a', (139971651561232, 139971651561312)), 1)]
```
i.e. that the cache is triggered once. Now multithread this:
```python
from concurrent.futures import ThreadPoolExecutor

pool = ThreadPoolExecutor(4)
fs = [pool.submit(my_useful_function) for _ in range(4)]

# main thread might not want to cache here but...
print(len(oe.sharing._SHARING_STACK))
# 4
```
And then check the results:
```python
for f in fs:
    print(f.result())
# []
# []
# [(('einsum', 'numpy', 'ab,ca->c', (139971651178784, 139971651181424)), 1)]
# [(('einsum', 'numpy', 'ab,bc->a', (139971651180624, 139971651180944)), 1)]
```
So the cache is missed. If you try
```python
cache = CounterDict()
fs = [pool.submit(my_useful_function, cache) for _ in range(4)]
```
You will see that cache is hit many times however.

---

Yeah one answer yes would be just to make ``oe.sharing._SHARING_STACK`` itself a dict. With ``threading.get_ident()`` as keys, and a list of caches as the values (to enable nested sharing). I might give that a go in a sec.
