### ISSUE TITLE
Make no memory limit the default?

### ISSUE THREAD

**Issue by jcmgray** [dgasmith/opt_einsum#55]
This is more a open question than a concrete suggestion. I'm just wondering if limiting the contraction memory to the largest input is the sensible choice for most use cases? I always turn it off, and need to to see best speedups for my use cases. In the contractions where memory *is* going to be an issue, limiting the possibly contractions results in exponentially slow progress anyway.

I'm just thinking that maybe a lot of contractions could be made faster by default for users not aware of this.

Anyway, I realise my use-cases are not everyones! And that this also might have also been influenced a bit by keeping maximum compatibility with numpy's einsum.

**Comment by dgasmith** [comment]
I think that your right, it doesn't make as much sense for this repository (NumPy probably still does). One drawback is that the cost of `optimal` will rise as we use the memory limit to sieve out early paths that have a very large cost. A couple thoughts:
 - We might want to look back into the optimal algorithm to see how we can still sieve bad paths, perhaps `if current_path_cost > naive cost` as a starting point.
 - Do we want to limit maximum memory in any way? Say current unused memory on the system.

**Comment by jcmgray** [comment]
* Yes, some heuristic path trimming approach might be nice. See [this paper](https://arxiv.org/abs/1304.6112) where it seems an optimal, exhaustive approach is possible for up to 25 tensors at once.

* Functionally, for me, it would be nice if ``opt_einsum`` just emitted a warning when a found path used more memory than was available. But not all backends use the same memory (dask-> disk, others-> GPU) so there's no real catch-all. You could have ``memory_limit={'warn', 'system', -1, int}`` or something.

**Comment by dgasmith** [comment]
Thinking back on this, it seems most of the concerns over limiting this functionality have not really come to fruition. I really like the `warn` idea overall.

**Comment by jcmgray** [comment]
Shall I leave this open in case we want to think about the ``'warn'`` and ``'system'`` options?

**Comment by dgasmith** [comment]
Closing this out, I think a `warn` is optimal at the moment. Testing frameworks are moving towards showing the warning by default so that users can catch deprecations early.
