### ISSUE TITLE
[BUG] Path flop count computation is nondeterministic in Python 3

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#62]
This came up in https://github.com/uber/pyro/issues/1427
```py
def test_path_flop_count():
    equation = 'bd,db,eac->ace'
    shapes = [(3, 2), (2, 3), (4, 2, 3)]
    operands = list(map(np.random.random, shapes))
    path = [(0, 1), (1, 0), (0,)]
    path, path_info = opt_einsum.contract_path(equation, *operands, path='greedy')
    print(path_info)  # "Optimized FLOP count" is nondeterministic
```
Admittedly this is kind of a weird path. See https://github.com/dgasmith/opt_einsum/pull/60#discussion_r221483126. Maybe the solution is to avoid paths like these, but I'm not sure how.

**Comment by fritzo** [comment]
cc @neerajprad

**Comment by dgasmith** [comment]
Interesting, I cannot reproduce this on my machine after ~40 iterations with Python 3.6. Can you comment more on the frequency of this discrepancy?

Looking over `helpers.flop_count` I don't see anything that could be non-deterministic, could be something in the input, however.

**Comment by fritzo** [comment]
@dgasmith sorry, you're right I was generating nondeterministic inputs in a test. Thanks for looking into this!

**Comment by dgasmith** [comment]
Glad you tracked this down! We do iterate over sets which give non deterministic orders and rely on the inner loop being communicative in a few places so I do worry about this.
