### ISSUE TITLE
Use best of many random greedy paths

### ISSUE THREAD

**Issue by jcmgray** [dgasmith/opt_einsum#63]
In quantum computing simulations particularly, finding the optimal contraction sequence has a huge effect on what is computable - the amount of memory and time required is exponential in how 'bad' the path found is. The greedy approach is generally worse than the optimal approach but it is cheap to compute (and even cheaper with #60!).

If we introduce a random greedy algorithm by tweaking the cost objective function, we get a variety of different paths with varying costs and we can just pick the best one. I had a little play with contracting a 49 qubit depth 20 circuit (661 tensors overall) and randomly adjusting each cost by +- 5%.

The following are 'contraction complexities' (maximum rank of tensor produced - ``2^this`` is the memory required which is also a rough proxy for computation time) on the left and frequency on the right from 100 runs.
```
[(25, 1),
 (27, 1),
 (28, 3),
 (29, 6),
 (30, 10),
 (31, 16),
 (32, 6),  # <- this is what the current greedy finds
 (33, 9),
 (34, 21),
 (35, 8),
 (36, 8),
 (37, 1),
 (38, 4),
 (39, 2),
 (40, 1),
 (42, 3)]
```
So the best contraction found vs the current contraction found requires ~128x less memory and computation, and turns the simulation from 'super'-computable to 'laptop'-computable.

**Comment by dgasmith** [comment]
This is found by modifying A/B/C as shown in #64 or is the randomization something else?

**Comment by jcmgray** [comment]
This was done by setting the cost as:
```python
cost = (
    (1 + 0.05 * randn()) * size12 - 
    (1 + 0.05 * randn()) * size1 - 
    (1 + 0.05 * randn()) * size2
)
```
You seem to get similar results for small amounts of randomness, then it gets much worse for large amounts of randomness (>50%).

**Comment by jcmgray** [comment]
It would also be a very simple way of parallelizing the path finding aspect of ``opt_einsum``.

**Comment by dgasmith** [comment]
That is pretty impressive, but in retrospect not terrible surprising I guess as the so called "shake" category of algorithms are based along similar ideas. We can change our existing algorithms to include this fairly easily and have a "shake" algorithm that would perform the meta evaluation of multiple runs. `shake-greedy`, `shake-cheap` etc.

If you have time, could you prototype out an example? I also have a bit this weekend to hack out some code as this look fairly straightforward.

**Comment by jcmgray** [comment]
Happy to implement this quite soon - I think it might be good to have #60 and #64 in before.

Just some thoughts on implementation. There's quite a lot of variables in choosing how the random algorithm might work:

- Run for a set number of iterations
- Run for a set amount of time
- Run until user presses ctrl+c?
- Run until a certain 'quality' is achieved? 
- Specify amount of randomness etc.

As quite an advanced feature it might conceptually be best to encapsulate all of those in a class that the user then supplies to to the `optimize` kwarg:
```python
optimizer = RandomGreedy(max_it=1000, max_t=60, random_strength=0.05, parallel=True)
oe.contract(..., optimize=optimizer)
```
or ``ShakeGreedy``, and maybe with some sensible defaults.

I haven't heard of "shake" algorithms. I was thinking of this more as an infinite temperature anneal - what would be really nice would be to randomly change parts of the contraction path only, which would be more like a finite temperature anneal. I suspect that is a lot more work however.

**Comment by dgasmith** [comment]
I think we want it pretty simple for users to use so that something like `shake-greedy` that implements what we think is best practice. For a first pass, I think a static length run in terms of a number of iterations is probably the way to go but written in such a way that we will likely expect additional features.

On the above API, I would imagine a user doing more like:

```
optimizer = RandomGreedy(string, **args) # Or whatever
path = optimizer.static_iterator(max_it=1000, random_strength=0.05, parallel=True)
oe.contract(..., optimize=path)
```

I don't particularly see a reason that we should change the `optimize` kwarg to accept callables at the moment.

**Comment by jcmgray** [comment]
Yes definitely agree a ready-to-go default ``'shake-greedy'`` is necessary.

One thing to note is that to generate the path first the equation and shapes would have to be supplied and then again with the contraction which is a slight inconvenience. This could still be an option though.

I was thinking of ``RandomGreedy`` as acting exactly like ``optimal``, ``greedy``, ``cheap`` once instantiated, so that it automatically fits in with all of ``contract``/``contract_path``/``contract_expression`` framework. Although it might be callable, a user would not have to think about that - more just a configuration holder.

However I imagine it might be a bit more obvious what is clean/possible once some code is written!

**Comment by jcmgray** [comment]
Rather than randomly adjusting the costs, another possible approach is to randomly select from the list of possible contractions according to some e.g. Boltzmann distribution based on their cost. The current, deterministic, greedy algorithm would then be the 'zero-temperature' version.

I might have a play with something like this at some point, as I can see some advantages to it.

**Comment by jcmgray** [comment]
I just had a little play with the 'temperature' version of this. The algorithm was:

1. Select the ``N`` best contractions, with costs ``c[i]``.
2. Compute weights ``w[i] = exp(-c[i] / T)`` (and normalize)
3. Randomly choose contraction based on probabilities ``w[i]``.

With ``N=8`` and ``T=0.05``, I get:
```python
[(24, 1),
 (25, 2),
 (26, 4),
 (27, 1),
 (28, 12),
 (29, 10),
 (30, 12),
 (31, 15),
 (32, 14),
 (33, 8),
 (34, 8),
 (35, 3),
 (36, 6),
 (37, 2),
 (38, 1),
 (40, 1)]
```
Which has a better cluster of high quality contractions - so this might be a more promising approach.

**Comment by dgasmith** [comment]
Are you normalizing the cost before the exponential, you will have issues with input size otherwise. I wouldn't quite qualify this one as inserting temperature, this is more or less the random algorithm above with a different random weight. You may to try much large sample sizes to get a handle on the true distribution, though I do see this version giving you more trouble in the long run.

**Comment by jcmgray** [comment]
> Are you normalizing the cost before the exponential, you will have issues with input size otherwise.

Yes you're right, I've been doing ``w[i] = exp(-(c[i] - min{c[i]}) / T)``. Thought of note, python's ``math.exp`` seems to handle arbitrarily negative ints: ``math.exp(-1e10000) == 0.0``.

I'm not quite sure how this would translate into a direct cost function - maybe exponentiation the cost first then randomly shifting it? There might be numeric problems that way, but yeah you'd want the probability that the contraction shifts to become the 'best' one to be inversely proportional to an exponential in its cost.

---

I think I should also note overall that this random method only seems to work when there are a lot of different possible 'opening moves', and isn't really beneficial for simple contractions. However, the gains are really significant (e.g. 256x better above) for certain tricky (and important) situations that it seems worth it.

**Comment by dgasmith** [comment]
With only a hundred runs it is hard to say, it looks like the average value is still `31` while the the best is only one better with the exponential where we have a long tail on the stats. Can you repost with ~10-100k runs so we can observe the statistics? The random value could specify the temperature to adjust how small or large the contract cost is smeared out by.

**Comment by jcmgray** [comment]
> Can you repost with ~10-100k runs so we can observe the statistics?

I'll try and get some good statistics for the various options + random strengths in the next few days.

> I still think we can squeeze this into a canonical annealing algorithm, I think I will try this weekend.

Great. I'm not an expert at these things, but to make the algorithm anneal properly would we have to freeze more and more of the path while we sample the remainder? E.g. at some point we would have selected the best path for the first half of the contraction while we still randomly sample from the second half?

> If not, can you provide a file that contains say 10-20 of your typical inputs?

For the moment I've [put a gist here](https://gist.github.com/jcmgray/9444ad3c36d3dd383fc94a031791d850) for one contraction of the type that appears in quantum circuit simulation (e.g. in this [paper](https://arxiv.org/abs/1807.04599)) - ``equation`` and ``shapes`` at the bottom. I'll try and generate a few more instances/types/sizes properly in the next few days.

**Comment by dgasmith** [comment]
Cool, do you have other contraction types that can be auto generated? Be good to get ourselves a set of perhaps 10-20.

**Comment by jcmgray** [comment]
@dgasmith I've made a repo with lots of 'tricky' sample contractions here - https://github.com/jcmgray/opt_einsum_samples. They are all in JSON format so simple to load.

**Comment by dgasmith** [comment]
@fritzo Would it be possible to generate perhaps a dozen or so examples with sizes of each index in a gist?

**Comment by fritzo** [comment]
@dgasmith Sure, I've created a PR in @jcmgray's repo, so as to keep all examples together: https://github.com/jcmgray/opt_einsum_samples/pull/1
