### ISSUE TITLE
Allow custom cost objective functions

### ISSUE THREAD

**Issue by jcmgray** [dgasmith/opt_einsum#64]
Experimenting with #60 and #63 made me think that allowing custom cost objective functions would be neat. The current the cost function greedy uses is
```python
size12 - size1 - size2
```
though as @fritzo notes, just using
```python
size12
```
made some contractions more deterministic and thus easier to cache.

Generally you might have:
```python
A * size12 - B * size1 - C * size2
```
with e.g. ``A``, ``B``, ``C`` random modifiers for #63. One might even try and learn the values using the contraction complexity / flop cost as a loss function.

**Comment by dgasmith** [comment]
Looking at it I think you are right, we could implement these as `if` statements and hardcode them in, but ultimately passing functions in would likely be more performant and easier to modify. We could have a stable of functions as well that could be shared between algorithms:

```
objective_functions = {
    "canonical": lambda s12, s1, s2: s12 - s1 - s2,
    "size12": lambda s12, s1, s1: s12,
    ....
}

**Comment by fritzo** [comment]
Hmm the objective functions I've been experimenting with don't fit into this framework, and might be difficult to abstract out without a very wide interface. E.g. I've been playing with objective function terms including:
- `len(k12 & output)`, encouraging contractions that result in few dimensions
- `len(k12 - dim_ref_counts[2])`, encouraging contractions on the periphery of the connectivity graph
- `len(k12) - len(k1 | k2)`, i.e. dim pressure, analogous to memory pressure
- "run Kruskal's algorithm; encourage contractions farthest away from contraction dims"

**Comment by jcmgray** [comment]
Probably all the information that might be needed is already passed to ``_get_candidate``? At least for the moment. In terms of performance, adding something like:
```python
if cost_func is None:
    cost = sizes[k12] - sizes[k1] - sizes[k2]
else:
    cost = cost_func(sizes, k12, k1, k2, ...)
```
should not add much overhead in the default case.
