### ISSUE TITLE
Help required optimizing the use of contract_expression

### ISSUE THREAD

**Issue by galah92** [dgasmith/opt_einsum#69]
Hi,

Thank you for this great library - I see a significant improvement in my performance already.

I'm facing a specific case where I got 4 matrices where only one of them is changing (real-time application). I'm successfully using the `contract_expression` like that:

    import numpy as np
    import opt_einsum as oe

    t = 51
    p = 51
    r = 27
    f = 56
    x = 35
    y = 39
    A = np.arange(x * t * f).reshape([x, t, f])
    B = np.arange(p * y * t * f).reshape([p, y, t, f])
    C = np.arange(f * r).reshape([f, r])
    D_shape = (y, x, f)

    expr = oe.contract_expression('yxf,xtf,pytf,fr->tpr',
                                D_shape, A, B, C,
                                constants=[1, 2, 3],
                                optimize='optimal')

    # this is called multiple times
    result = expr(D)  # D.shape == D_shape

But this doesn't yield performance improvement compared to default `np.einsum`.

In this scenario I can easily `np.transpose` `A`, `B`, `C` (and even `D`) in a way that'll yield the best path. I can change the order of the expression, and basically play with is as I'd like in order to get to the optimal path.

Is there a way to do that using the library? I don't have intuition regarding what will yield the best performance.

Thanks!

**Comment by jcmgray** [comment]
If I try your snippet I find that ``expr(D)`` is about 2000x quicker than:
```python
np.einsum('yxf,xtf,pytf,fr->tpr', D, A, B, C)
```
Some versions of ``numpy`` have ``optimize=True`` that essentially uses ``opt_einsum`` already? Moreover, if you:
```python
>>> print(expr)
<ContractExpression('yxf,[xtf,pytf,fr]->tpr', constants=[1, 2, 3])>
  1.  'xtf,yxf->tfy'
  2.  'tfy,pytf->tfp'
  3.  'tfp,fr->tpr' [TDOT]
```
You can see that ``D`` is needed for the first contraction and thus there are no constant contractions to perform, which is maybe another reason you don't see any speedup.

**Comment by jcmgray** [comment]
Not easily.. as you have found, choosing the non-optimal path (where ``D`` is not used first) produces much much slower contractions. If you really wanted to do ``D`` last you could explicitly perform ``oe.contract("xtf,pytf,fr->{whichever}", A, B, C)`` first. This might be huge and slow though!

**Comment by dgasmith** [comment]
For this particular problem it appears not contracted `D` is actually slower as you force a N^^ algorithm I believe rather than keeping everything N^4.

I was thinking we might be able to automate the creation of temporaries as suggestion above, but I do not see many cases where this is more optimal than letting the canonical algorithms find the best path and stopping when the constant tensor is first used.

**Comment by galah92** [comment]
I understand, though it's still counter-intuitive to me that I can't permute these matrices somehow to generate a better path. and that the "optimal" algorithm is better then the "greedy" one.
Thank you.

**Comment by jcmgray** [comment]
Hmm do you have a faster path in mind that you can do manually? Just to clarify, The optimal path is really checking every single permutation of inputs and contraction orders, so one cannot  fundamentally do better than that in terms of optimizing a single contraction.

**Comment by galah92** [comment]
I guess I'm convinced.. This is probably the best we can do. Thank you for your help.

**Comment by dgasmith** [comment]
Thanks for the report. Do let us know if you run across additional problem cases and we will see if we can do better. Unfortunately, it looks like this case is as good as it is going to get.
