### ISSUE TITLE
Python2 Deprecation Plan

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#79]
As Python2 will cease to be supported in 2020 and many Python projects have cut their last release of a Py2 compliant module (NumPy, SciPy, Pandas, iPython, SciKitLearn, [etc]( https://python3statement.org)) we may want to consider doing the same. The cleanup in this project is pretty low when considering the removal of Py2, so I do not see this as very urgent. I would be curious if anyone had thoughts as to this direction.

@fritzo @jcmgray

**Comment by jcmgray** [comment]
I've actually never used python2 so that would be fine by me! On the other hand, maintaining py2 support seems to have been pretty easy so far given the unit tests/travis etc.

**Comment by fritzo** [comment]
Pyro will be supporting Python 2 as long as PyTorch does. I've heard PyTorch will soon drop Python 2 support, but I do not know their timeline.

**Comment by dgasmith** [comment]
I could not find a PyTorch blog or issue, but considering PyTorch does depend on NumPy I would suspect not too much longer as well.

Having our last minor release for Py2 coincide with PyTorch's last Py2 minor release seems like a reasonable approach. We can patch whatever release that may be until 2020 to correspond to Python deprecation cycles. If there are no objections and this sounds reasonable lets plan for this.

I suspect v2.4 will be our last Py2 release.

**Comment by fritzo** [comment]
Soumith on the PyTorch team tells me

> [PyTorch has] no plans on dropping Python 2.7 support at the moment. The downloads breakdown shows that Python 2.7 is around 25% of marketshare, and we don't plan to disappoint so many users until that downloads number drops significantly, or if something happens in the rest of the python ecosystem that forces us to re-evaluate.

If it's not too much work, it would be great if `opt_einsum` could maintain Python 2 support while PyTorch does. @neerajprad and I are happy to help out if needed. If you do drop Python 2 support, I guess we can pin Pyro to `opt_einsum==v2.3` temporarily.

**Comment by dgasmith** [comment]
Oh, interesting, I guess PyTorch will pin NumPy for awhile in that case. Py2 isn't really affecting us here so I see no real reason to drop beyond the fact that we could clean up a few minor areas. 

This does not really alter the plan of keeping Py2 until PyTorch's last Py2 release, that just may be farther out than v2.4.

@fritzo Thank you for the feedback.

**Comment by fritzo** [comment]
FYI Pyro is planning to [drop support for Python 2](https://github.com/pyro-ppl/pyro/issues/1935) in the next minor release (0.4 planned for ~August).

**Comment by dgasmith** [comment]
@fritzo That is really good to know. Would it effect you if we dropped Py3 support for 3.0 (likely this month)? It seems the feature mismatch for your Py2.7 users would be minimal.

**Comment by fritzo** [comment]
It would be fine for Pyro users if you drop Py2 support in your 3.0 release. We'll pin Pyro's final Py2 release to the current opt_einsum release.

**Comment by dgasmith** [comment]
Great, I vote for dropping Py2 in the 3.0 release in this case. I show about 15-20% usage from PyPI stats from Py2, but this change should not effect them unless they really require new features.

We do not necessarily *need* to drop Py2, but if we do not drop it now it could be quite some time in the future before we would have a release that would make sense to do so. As our only dependency (NumPy) has dropped Py2 as well, I think it makes sense to do so now. This will also give us more flexibility in the future if we need Py3 features.
