### ISSUE TITLE
FR: separate 'auto' strategy out of contract_path

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#82]
The 'auto' strategy is really nice, but it requires actual arrays because it is based into `contract_path`. Sometimes I want to get a path based merely on shapes. It should be easy to factor out the logic from `contract_path` to a new `paths.auto` that conforms to the standard shape-based path interface.

**Comment by jcmgray** [comment]
Yes this seems like a very good idea to factor out the logic. 

As a side note, it would be nice to be able to supply shapes to ``contract_path``, maybe a ``shapes=False/True`` kwarg?
