### ISSUE TITLE
v3.0 Planning

### ISSUE THREAD

**Issue by dgasmith** [dgasmith/opt_einsum#83]
We are planning a major version bump for the following reasons:
 - Transition to be backend agnostic (NumPy is no longer the principle backend).
   - See #81 which has the (small) potential to break current implementations.

TODO Items:
 - [ ] Refactoring in preparation for NEP18 (#46) should be considered.
 - [ ] Consider adding a Ricci calculus parser `contract('A_ij B_jk A_kl', {"A": a, "B": b})`.
 - [x] Run through the backends to check where we can refactor.
 - [x] Update docs and README to reflect that we are NumPy agnostic.
 - [ ] Consider parsers that use metrics besides raw FLOPS (actually trying out several contraction paths for example).

Are there other items where we might need to do a few (small) compatibility breaks that would be good for future sustainability?

**Comment by jcmgray** [comment]
Another small thing might be to fully deprecate/remove the `path` kwarg.

**Comment by dgasmith** [comment]
I think a lot of the above involves somewhat wishlist items. I think becoming backend agnostic is the primary change to 3.0. The only thing to do is to make a docs pass to reflect this change.

@fritzo Would you mind double checking that Pyro works with the current master? I will follow up with other projects before we make this change.

**Comment by fritzo** [comment]
@dgasmith thanks for the ping. Yes Pyro appears to work with opt_einsum master.

**Comment by dgasmith** [comment]
@fritzo Awesome! Thanks for checking.

**Comment by dgasmith** [comment]
We haven't talked about NEP18 much, but looking into current implementations there is effectively nothing for us to do beyond slowly removing the current backend technology as more packages pick up this standard. Realistically, this likely means nothing to do for ~6 months to a year as this is hammered out.

Beyond that, I think a decision on #91 is the last thing we need to do here?

**Comment by dgasmith** [comment]
Since @Thenerdstation is looking for new features I will work on the 3.0 release this week. @jcmgray @fritzo any blockers here?

**Comment by fritzo** [comment]
@dgasmith I see no blockers from Pyro.

**Comment by Thenerdstation** [comment]
We don't really have any feature requests other than the Cython implementation, which I'm happy to try to help build!

**Comment by dgasmith** [comment]
That would be fantastic on the Cython implementation! I will try to jot down some notes on your issue this weekend about possible pitfalls and enhancements.

**Comment by jcmgray** [comment]
No blockers from me. And cython versions of the path optimizers would be fantastic I think.

**Comment by dgasmith** [comment]
v3 release minted, if anyone would like to try out the code before I push out releases to PyPI/Conda let me know.

**Comment by dgasmith** [comment]
v3 on PyPI and now rolling out to conda-forge. Thank you everyone for many excellent features this release!
