### ISSUE TITLE
FR: cache hit/miss data

### ISSUE THREAD

**Issue by liwt31** [dgasmith/opt_einsum#85]
It would be nice to have something like this (partly copied from the document)
```
# copied
with shared_intermediates() as cache:
    marginals = {output: contract('{}->{}'.format(inputs, output), *factors)
                 for output in 'abcdef'}
# new ideas
print(cache.hit)
print(cache.miss)
```
If I understand correctly `cache` is now a simple dictionary and no direct operaetion on the variable is documented, so adding some new attributes won't be very difficult.

**Comment by jcmgray** [comment]
I think you can [supply](https://optimized-einsum.readthedocs.io/en/latest/autosummary/opt_einsum.sharing.shared_intermediates.html#opt_einsum.sharing.shared_intermediates) any dict-like object to ``shared_intermediates``, including a ``CounterDict`` or something. Might that address your needs?

**Comment by liwt31** [comment]
Thank you for the reminder! A brilliant idea.

**Comment by jcmgray** [comment]
A slight subtlety is that the ``shared_intermediates`` code uses ``if k in cache`` not ``try: cache[k]``. Here's an implementation that works in case its useful (and for future reference):

```python
class HitDict(dict): 
     
    def __init__(self, *args, **kwargs): 
        self.gets = 0 
        self.hits = 0 
        super().__init__(*args, **kwargs)

    def __contains__(self, k):
        self.gets += 1
        does_contain = super().__contains__(k)
        if does_contain:
            self.hits += 1
        return does_contain

    @property
    def misses(self):
        return self.gets - self.hits
```

In action:
```python
import opt_einsum as oe
import numpy as np

eq, shapes = oe.helpers.rand_equation(5, 3)
views = [np.random.rand(*s) for s in shapes]

cache = HitDict()

with oe.shared_intermediates(cache):
    oe.contract(eq, *views)
    oe.contract(eq, *views)
    oe.contract(eq, *views)

cache.gets
# 12

cache.hits
# 8

cache.misses
# 4
```
