### ISSUE TITLE
Potential bug (outer tensor product)

### ISSUE THREAD

**Issue by fischbacher** [dgasmith/opt_einsum#86]
This works...:

```python
>>> import mpmath
>>> import numpy
>>> m0 = numpy.eye(2)
>>> opt_einsum.contract('bc,ad->abcd', m0, m0)
array([[[[1., 0.], ...)
```

...but this breaks:

```python
>>> m1 = m0 + mpmath.mpc(0)
>>> opt_einsum.contract('bc,ad->abcd', m1, m1)
Traceback (most recent call last): (...)
TypeError: invalid data type for einsum
```

However, using opt_einsum with mpmath is otherwise OK in principle:

```python
>>> opt_einsum.contract('bc,cd->bd', m1, m1)
array([[mpc(real='1.0', imag='0.0'), mpc(real='0.0', imag='0.0')],
       [mpc(real='0.0', imag='0.0'), mpc(real='1.0', imag='0.0')]],
      dtype=object)
```

**Comment by dgasmith** [comment]
The first example uses pure `einsum` while the second will hit `np.dot`, I believe they have different behaviors. This should work by implicitly converting them to NumPy object arrays. Does `mpmath` have a built in array type?

PS: I formatted you post with backticks which help with readability.

**Comment by fischbacher** [comment]
Note that the way I am building m1 above does actually give me a dtype=object numpy array.

mpmath has built-in array types, but I am not using them, since there is no einsum-equivalent. ;-)

**Comment by jcmgray** [comment]
Yeah the problem is just that ``numpy.einsum`` is being invoked which doesn't support ``dtype=object``. One potential & v simple fix would be to add a ``backend='numpy-no-einsum'`` option to always prefer tensordot.

(Just checked and this indeed fixes the second contraction.)
