### ISSUE TITLE
Separate symbolic path optimization from tensor backend?

### ISSUE THREAD

**Issue by fritzo** [dgasmith/opt_einsum#90]
I really like that opt_einsum provides a pure-python dispatch mechanism that we can essentially use for symbolic computation. I'm opening this issue to discuss how we might **further** separate the path optimizer (which is purely symbolic) from the backend dispatch mechanism. (They are already mostly independent.)

## Examples

Here are a couple cool examples of purely symbolic path optimization, unrelated to tensor contraction:
1. Kevin Murphy's [variable elimination code](https://github.com/probml/pyprobml/blob/4ede64b4cebf8a9c7fc40d5b14c5dd76c5667e50/scripts/bayesnet_inf_autodiff.py#L134) that uses `np.einsum_path` as an alternative to the Junction Tree algorithm for inference in graphical model. When these models are limited to discrete random variables, this example is equivalent to tensor contraction; however it generalizes to e.g. Gaussian variable elimination which is distinct from tensor contraction and really wants a different objective function.
2. @eb8680 and I are similarly using the greedy optimizer to [optimize sum-product expressions](https://github.com/pyro-ppl/funsor/blob/14766efd8d5da091cb78e92a788f9fd25301de0b/funsor/optimizer.py#L174) involving not only sums but integrals, again typically Gaussian integrals.

One interesting aspect of both these examples is that, whereas tensor contraction cost is exponential space in time in the number of dimensions (of say fixed size), Gaussian contraction is only quadratic in space and cubic (or just sub-cubic) in number of dimensions. Thus Gaussian contractions should use a different FLOP computaiton.

**Comment by jcmgray** [comment]
To put in in rather formal terms, would I be correct in saying the unifying feature is the search for a binary tree that reduces ``N`` inputs to a single output, with some cost associated with the creation of each vertex in the tree?

The ``greedy`` function does now accept ``cost_fn`` for 'locally' assigning a cost to choosing with pair of tensors to contract, but I agree it would be nice to have the *total* path cost also be customizable.

**Comment by fritzo** [comment]
Thanks @jcmgray , yes I think `cost_fn()` will work for all cases I can think of. E.g. to perform variable elimination in a factor graph with both discrete and Gaussian variables, we could pass in side information about the type of each variable:
```py
class VariableEliminationCostFn(object):
    def __init__(self, var_types, size_dict):
        self.var_types = var_types  # dict mapping var name to {"discrete", "gaussian"}
        self.size_dict = size_dict  # dict mapping var name to size
    def memory(self, dims):
        gaussian_dim = sum(self.size_dict[k] for k in dims
                           if self.var_types[k] == "gaussian")
        memory = 1 + gaussian_dim + gaussian_dim ** 2  # total, mean, covariance
        for k in dims:
            if self.var_types[k] == "discrete":
                memory *= self.size_dict[k]
        return memory
    def __call__(self, size12, size1, size2, k12, k1, k2):
        return self.memory(k12) - self.memory(k1) - self.memory(k2)

cost_fn = VariableEliminationCostFn(var_type={'x': 'discrete', 'y': 'gaussian', ...}, size_dict=...)
```
@eb8680 maybe we should use something like this.

**Comment by dgasmith** [comment]
I do like this idea. Anyone have some time to take an initial crack at it? The refactoring @jcmgray has done in the past should make this much more straightforward.

**Comment by dgasmith** [comment]
Looking into this again, I think we can handle a more generic cost function transparently and is not a 3.0 blocker. Any thoughts here?

**Comment by fritzo** [comment]
I think there is no blocker. The example `VariableEliminationCostFn` above already works transparently, I just didn't realize it was possible before opening this issue. I think we can close, or maybe consider documenting an example of a cost function like the one above. @jcmgray thanks for the help!
