### ISSUE TITLE
Missing path_random in pip3 install

### ISSUE THREAD

**Issue by Thenerdstation** [dgasmith/opt_einsum#93]
It seems like `opt_einsum.path_random` is missing from the pip install package.

Version: 2.3.2

```python
>>> import opt_einsum
>>> opt_einsum.__version__
'v2.3.2'
>>> dir(opt_einsum)
['__builtins__', '__cached__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'backends', 'blas', 'compat', 'contract', 'contract_expression', 'contract_path', 'get_symbol', 'helpers', 'parser', 'paths', 'shared_intermediates', 'sharing']
>>> opt_einsum.path_random
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'opt_einsum' has no attribute 'path_random'
```

**Comment by dgasmith** [comment]
Well... thats very odd since we use recursive includes in the MANIFEST and auto detection in the setup. Let me check this out tonight and I will push out a patch.

Thank you for bringing this up.

**Comment by Thenerdstation** [comment]
`opt_einsum.paths.PathOptimizer` is also missing.

**Comment by dgasmith** [comment]
Ah, this is a docs issue. The functions you are after are in the current master, but not in the release. I have changed the RTD builds to default to the last stable release not master.

**Comment by Thenerdstation** [comment]
Great! Let me know when it's pushed and we'll include it in TensorNetwork

**Comment by dgasmith** [comment]
v3.0 is now on pip and rolling out to Conda-forge soon! Give it a try.
