### ISSUE TITLE
`import opt_einsum` fails due to jax.py

### ISSUE THREAD

**Issue by skye** [dgasmith/opt_einsum#98]
Importing opt_einsum 3.0.0 fails for me due to the new jax backend:
```
In [1]: import opt_einsum
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c4cbb6c93042> in <module>()
----> 1 import opt_einsum

.../opt_einsum/__init__.py in <module>()
      7 from . import paths
      8 from . import path_random
----> 9 from .contract import contract, contract_path, contract_expression
     10 from .parser import get_symbol
     11 from .sharing import shared_intermediates

.../opt_einsum/contract.py in <module>()
      8 import numpy as np
      9 
---> 10 from . import backends
     11 from . import blas
     12 from . import helpers

.../opt_einsum/backends/__init__.py in <module>()
      5 # Backends
      6 from .cupy import to_cupy
----> 7 from .dispatch import (get_func, has_einsum, has_tensordot, build_expression, evaluate_constants, has_backend)
      8 from .tensorflow import to_tensorflow
      9 from .theano import to_theano

.../opt_einsum/backends/dispatch.py in <module>()
     10 
     11 from . import cupy as _cupy
---> 12 from . import jax as _jax
     13 from . import tensorflow as _tensorflow
     14 from . import theano as _theano

.../opt_einsum/backends/jax.pyc in <module>()
     13 
     14     @to_backend_cache_wrap
---> 15     @jax.jit
     16     def to_jax(x):
     17         return x

AttributeError: 'module' object has no attribute 'jit'
```

I think the `import jax` at https://github.com/dgasmith/opt_einsum/blob/master/opt_einsum/backends/jax.py#L12 is importing itself since the file is named jax, instead of importing the installed library jax.

Once this is fixed, I suspect there'll be a circular import, since jax imports opt_einsum! https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L38 I'm not sure how best to resolve this -- the best I can come up with is one of us adds a "lazy" import inside a function, instead of at the top of the file, but maybe you can think of something more elegant. Maybe since jax already calls opt_einsum the jax backend isn't necessary?

BTW, glad to see you're interested in jax! :)

**Comment by jcmgray** [comment]
I can't seem to reproduce this, at least with the current pip jax + jaxlib, is the inclusion of opt_einsum in jax more recent that those versions? 

Also what version of python are you using? python2 support was dropped in opt_einsum v3.0 including several ``from __future__ import absolute_import`` statements which might also cause this problem.

**Comment by dgasmith** [comment]
Betting this is the Python2 changes as well. Though the setup.py should throw Python2 conflicts upon installation if I am reading those docs correctly.

**Comment by dgasmith** [comment]
Thank you for bringing this up! 3.0.0 was our last release that support Python 2 and did not correctly flag Python 3.5+ for PyPI. This has now been fixed and downloading `opt_einsum` on Python 2 now correctly install the last Python 2 compatible `opt_einsum` release:

```bash
Collecting opt_einsum
  Using cached https://files.pythonhosted.org/packages/f6/d6/44792ec668bcda7d91913c75237314e688f70415ab2acd7172c845f0b24f/opt_einsum-2.3.2.tar.gz
Requirement already satisfied: numpy>=1.7 in ./anaconda3/envs/py2/lib/python2.7/site-packages (from opt_einsum) (1.16.4)
Building wheels for collected packages: opt-einsum
  Building wheel for opt-einsum (setup.py) ... done
  Created wheel for opt-einsum: filename=opt_einsum-2.3.2-cp27-none-any.whl size=49883 sha256=9f0062e586a428e92b8cd506b929c386d6fd10a89200e6b5c2866f03af268f29
  Stored in directory: /Users/daniel/Library/Caches/pip/wheels/51/3e/a3/b351fae0cbf15373c2136a54a70f43fea5fe91d8168a5faaa4
Successfully built opt-einsum
Installing collected packages: opt-einsum
Successfully installed opt-einsum-2.3.2
```

Please do uninstall/reinstall opt_einsum to verify.

**Comment by skye** [comment]
Ah, I was indeed using Python 2 originally. I verified that everything works as expected in both Python 2 and Python 3 now. Thanks!
